server:
  port: 8010

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: organization
  rabbitmq:
    host: ${RABBIT_MQ_HOST:39.108.153.211}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:jean}
    password: ${RABBIT_MQ_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:39.108.153.211}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300
    password: ${REDIS_PASSWORD:56155481}
  datasource:
    url: jdbc:${DATASOURCE_DB:mysql}://${DATASOURCE_HOST:39.108.153.211}:${DATASOURCE_PORT:3306}/springCloud
    username: ${DATASOURCE_USERNAME:test}
    password: ${DATASOURCE_USERNAME:Jean123.456}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8
#  resources:
#    add-mappings: false

logging:
  level:
    com.springboot.cloud: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)
