server:
  port: 8031

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: turbine
  rabbitmq:
    host: ${RABBIT_MQ_HOST:198.13.45.205}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:jean}
    password: ${RABBIT_MQ_PASSWORD:123456}

turbine:
  stream:
    port: 8989

management:
  server:
    port: 8989
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  level:
    org.springframework.web: debug
  path: logs/
  file:
    max-size: 1GB