server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: authorization-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:39.108.153.211}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:jean}
    password: ${RABBIT_MQ_PASSWORD:123456}
  redis:
    host: ${REDIS_HOST:39.108.153.211}
    port: ${REDIS_PORT:6379}
    password: ${REDIS_PASSWORD:56155481}
  datasource:
    url: jdbc:${DATASOURCE_DB:mysql}://${DATASOURCE_HOST:39.108.153.211}:${DATASOURCE_PORT:3306}/springCloud
    username: ${DATASOURCE_USERNAME:test}
    password: ${DATASOURCE_USERNAME:Jean123.456}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.cj.jdbc.Driver}

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0

  mvc:
    throw-exception-if-no-handler-found: true

  #jwt的密钥
  security:
    oauth2:
      jwt:
        signingKey: 123456

logging:
  level:
    org.springframework.web: debug
    org.springframework.security: debug
    com.springboot.auth: debug
    org.apache.ibatis: debug
    java.sql.PreparedStatement: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true
