
#服务端口
server:
  port: 8888
#注册到服务中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: config-bus-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:39.108.153.211}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:jean}
    password: ${RABBIT_MQ_PASSWORD:123456}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RubyJing/SpringCloudConfigExample
          searchPaths: ${SEARCHPATHS:/config-repo}
#          username: yourName
#          password: yourPassword
      lable: ${LABEL:master}
#      fail-fast: true
    bus:
      enabled: true
      trace:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh