#服务端口
server:
  port: ${EUREKA_PORT:8761}

eureka:
  client:
    # 避免服务注册自己
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  application:
    name: eureka-server
  rabbitmq:
    host: ${RABBIT_MQ_HOST:198.13.45.205}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:jean}
    password: ${RABBIT_MQ_PASSWORD:123456}