server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_ZONE_HOST:localhost}:${EUREKA_ZONE_PORT:8761}/eureka/

spring:
  rabbitmq:
    host: ${RABBIT_MQ_HOST:localhost}
    port: ${RABBIT_MQ_PORT:5672}
    username: ${RABBIT_MQ_USERNAME:guest}
    password: ${RABBIT_MQ_PASSWORD:guest}
  redis:
    host: ${REDIS_HOST:198.13.45.205}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 300
   # password: ${REDIS_PASSWORD:56155481}
  datasource:
    url: jdbc:${DATASOURCE_DB:mysql}://${DATASOURCE_HOST:198.13.45.205}:${DATASOURCE_PORT:3306}/springCloud
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:zjp123}
    driver-class-name: ${DATASOURCE_DRIVER:com.mysql.jdbc.Driver}

  zipkin:
    enabled: true
    sender:
      type: rabbit
  sleuth:
    sampler:
      probability: 1.0
    web:
      client:
        enabled: true
  mvc:
    throw-exception-if-no-handler-found: true
  servlet:
    multipart:
      max-request-size: "2MB"
      max-file-size: "2MB"
  jackson:
    time-zone: GMT+8
#  resources:
#    add-mappings: false

logging:
  level:
    java:
      sql:
        PreparedStatement: debug
    com:
      springboot: debug
  path: logs/
  file:
    max-size: 1GB

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  configuration:
    map-underscore-to-camel-case: true

mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO # 0为AUTO
      logic-delete-value: "Y" # 逻辑已删除值(默认为 Y)
      logic-not-delete-value: "N" # 逻辑未删除值(默认为 N)
 # config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  #输出sql执行语句
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl